export const PLATFORM_CODE = 'PLATFORM_CODE'

export const SMSDIALOG_VISIBLE = 'SMSDIALOG_VISIBLE'

export const PLAT_FORM = 'PLATFORM'

export const DIALOG_TITLE = 'DIALOG_TITLE'

export const CHECKED_SELECTATTR = 'CHECKED_SELECTATTR'

export const SELECT_ATTR = 'SELECT_ATTR'

export const PLATFORMCODE_STEP = 'PLATFORMCODE_STEP'
